# Generated by Django 4.0.4 on 2022-04-17 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qldl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
