# Generated by Django 4.0.4 on 2022-04-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qldl', '0002_remove_user_role_delete_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='thoi_gian',
            field=models.IntegerField(default=0),
        ),
    ]
