# Generated by Django 4.0.4 on 2022-04-25 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qldl', '0004_remove_dondattour_loai_ve_dondattour_loai_ve'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='like',
            name='tin_tuc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like', to='qldl.tintuc'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('khach_hang', 'tin_tuc')},
        ),
        migrations.RemoveField(
            model_name='like',
            name='tour',
        ),
    ]
