# Generated by Django 4.0.4 on 2022-05-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qldl', '0006_dondattour_tong_tien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='so_dien_thoai',
            field=models.CharField(max_length=20),
        ),
    ]
