# Generated by Django 4.0.4 on 2022-06-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qldl', '0008_role_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
