# Generated by Django 4.0.4 on 2022-10-08 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qldl', '0010_role_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaive',
            name='don_gia',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_anh', models.ImageField(default=None, upload_to='uploads/%Y/%m')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='qldl.tour')),
            ],
        ),
    ]
