# Generated by Django 4.0.4 on 2022-10-09 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qldl', '0012_tourimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tintuc',
            name='short_desc',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='TinTucImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hinh_anh', models.ImageField(default=None, upload_to='uploads/%Y/%m')),
                ('tin_tuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='qldl.tintuc')),
            ],
        ),
    ]
